// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Sepll2.FromJson(jsonString);

namespace CharacterGenerator
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class Sepll2
    {
        [JsonProperty("casting_time")]
        public string CastingTime { get; set; }

        [JsonProperty("components")]
        public string Components { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }

        [JsonProperty("level")]
        public long Level { get; set; }

        [JsonProperty("range")]
        public string Range { get; set; }

        [JsonProperty("school")]
        public School School { get; set; }
    }

    public enum School { Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, Transmutation };

    public partial class Sepll2
    {
        public static Dictionary<string, Sepll2> FromJson(string json) => JsonConvert.DeserializeObject<Dictionary<string, Sepll2>>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dictionary<string, Sepll2> self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                SchoolConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class SchoolConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(School) || t == typeof(School?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Abjuration":
                    return School.Abjuration;
                case "Conjuration":
                    return School.Conjuration;
                case "Divination":
                    return School.Divination;
                case "Enchantment":
                    return School.Enchantment;
                case "Evocation":
                    return School.Evocation;
                case "Illusion":
                    return School.Illusion;
                case "Necromancy":
                    return School.Necromancy;
                case "Transmutation":
                    return School.Transmutation;
            }
            throw new Exception("Cannot unmarshal type School");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (School)untypedValue;
            switch (value)
            {
                case School.Abjuration:
                    serializer.Serialize(writer, "Abjuration");
                    return;
                case School.Conjuration:
                    serializer.Serialize(writer, "Conjuration");
                    return;
                case School.Divination:
                    serializer.Serialize(writer, "Divination");
                    return;
                case School.Enchantment:
                    serializer.Serialize(writer, "Enchantment");
                    return;
                case School.Evocation:
                    serializer.Serialize(writer, "Evocation");
                    return;
                case School.Illusion:
                    serializer.Serialize(writer, "Illusion");
                    return;
                case School.Necromancy:
                    serializer.Serialize(writer, "Necromancy");
                    return;
                case School.Transmutation:
                    serializer.Serialize(writer, "Transmutation");
                    return;
            }
            throw new Exception("Cannot marshal type School");
        }

        public static readonly SchoolConverter Singleton = new SchoolConverter();
    }
}